// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUr_uLFjkPDzp4g8-S5ywocjtbAl1fAFM',
    appId: '1:16426504801:android:4ec04fae92f48e3a941020',
    messagingSenderId: '16426504801',
    projectId: 'newket-94290',
    storageBucket: 'newket-94290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCoxYQCnWQB-nihFUO1AKfVhpaJmBz9nc',
    appId: '1:16426504801:ios:97d331f4e16ce147941020',
    messagingSenderId: '16426504801',
    projectId: 'newket-94290',
    storageBucket: 'newket-94290.firebasestorage.app',
    androidClientId: '16426504801-e8q2kaj9sgb6e55f4lk2b22914fifncs.apps.googleusercontent.com',
    iosClientId: '16426504801-6mdj2o4k4pkmno08fqipajvq809f8urq.apps.googleusercontent.com',
    iosBundleId: 'com.newket.soyaa',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDROt8bog9y00mF5dXvrELRgxtKh8MY56M',
    appId: '1:16426504801:web:0762fca9e4fabff3941020',
    messagingSenderId: '16426504801',
    projectId: 'newket-94290',
    authDomain: 'newket-94290.firebaseapp.com',
    storageBucket: 'newket-94290.firebasestorage.app',
    measurementId: 'G-3MKEE6G98H',
  );

}